### PR TITLE
Improve RSS feed

### PR DESCRIPTION
**Pull request by imdj**
These are a set of changes to fix issues related to RSS feed as mentioned in
- #696 

Note: I took the liberty to adjust some versions in `package.json` for better compatibility, as `eslint-config-next@11.1.4` was giving an false positive error about `no-document-import-in-page` and causing build failure

### CODE REVIEW

**Comment by imdj** [comment]
I fixed the build errors
This should now produce the desired feed which looks like this:

image

**Comment by davesnx** [comment]
Thanks for the PR, I pushed directly to main myself

**Comment by davesnx** [comment]
Took your code to make https://github.com/davesnx/sancho.dev/commit/cc408549a132f44753682f2533a69d363f57c250

Thanks for the PR <3

**Comment by imdj** [comment]
No problem, my pleasure.
The feed looks good 👌

**Pull request closed without merging**
